name: Check for TODO comments

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  todo-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Search for TODO comments
      run: |
        # Find TODOs in the codebase
        if grep -r --include=\*.cs "TODO" .; then
          echo "TODOs found. Please address them before merging."
          exit 1
        else
          echo "No TODOs found. All good!"
        fi
